name = "Statics Health Multiplier"
uid = "b8d941e131multiplier"
version = 1.1
copyright = ""
description = "All static units have health and shield points multiplied by number noted in config."
author = "Balthazar (edit by Sad Turtle Man)"
--icon = "/mods/BrewLAN_Gameplay/WaterGuard/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
